<?php
namespace MNHN\PortailBundle\Repository;

/**
 * P_Program_ObjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class P_Program_ObjectiveRepository extends \Doctrine\ORM\EntityRepository
{
}