<?php
namespace MNHN\PortailBundle\Repository;

/**
 * P_ProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class P_ProgramRepository extends \Doctrine\ORM\EntityRepository
{
}