<?php
namespace MNHN\PortailBundle\Repository;

/**
 * P_StructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class P_StructureRepository extends \Doctrine\ORM\EntityRepository
{
}