<?php

namespace MNHN\PortailBundle\Repository;

/**
 * PartnersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnersRepository extends \Doctrine\ORM\EntityRepository
{
}
