<?php

namespace SiteBundle\Repository;

/**
 * GeomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeomRepository extends \Doctrine\ORM\EntityRepository
{
}
