<?php
namespace SiteBundle\Repository;

/**
 * Page_ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Page_ContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPageContentByPositionFilter($pageSlug, $position)
    {
        $qb = $this->createQueryBuilder('pc');
        $qb->join("pc.page","page")
            ->where("page.slug = :slug")
            ->andWhere('pc.position LIKE :position')
            ->setParameters(array('slug' => $pageSlug, 'position' => $position.'%'))
            ->orderBy('pc.position', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }

}
