<?php

namespace MNHN\PortailBundle\Repository;

/**
 * Program_ResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Program_ResultsRepository extends \Doctrine\ORM\EntityRepository
{
}
