<?php

namespace MNHN\AdminBundle\Repository;

/**
 * F_FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class F_FieldRepository extends \Doctrine\ORM\EntityRepository
{
}
