<?php

namespace AdminBundle\Repository;

/**
 * G_ListItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class G_ListItemRepository extends \Doctrine\ORM\EntityRepository
{
}
