<?php

namespace BuilderBundle\Repository;

/**
 * DBLogCorrespondenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DBLogCorrespondenceRepository extends \Doctrine\ORM\EntityRepository
{
}