<?php

namespace BuilderBundle\Repository;

/**
 * F_FormFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class F_FormFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
