<?php

namespace BuilderBundle\Repository;

/**
 * G_ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class G_ListRepository extends \Doctrine\ORM\EntityRepository
{
}
