<?php

namespace BuilderBundle\Repository;

/**
 * Menu_PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Menu_PageRepository extends \Doctrine\ORM\EntityRepository
{
}
